import React from "react";
import Image from "next/image";
import {
  Box,
  Button,
  Card,
  CardBody,
  CardHeader,
  Container,
  Heading,
  Text
} from "@chakra-ui/react";
import Head from "next/head";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Hero from "@/components/Hero";
import DAL_rvsd from "../components/DAL_rvsd.png";
import { useRouter } from "next/router";

const Home: React.FC = () => {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>DataLink</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <Container maxW="70%" centerContent>
        {/* DATADAO LOGO */}

        <Box className="logo" display='flex' mt='2' alignItems='center'>
          <Image src={DAL_rvsd} alt="logo" width={480} height={480} />
        </Box>

        {/* <Text fontSize="4xl" color='black' as='b'>
        Buidling the most accessible Web3 data validation and data-sharing tools.
        </Text> */}

        <br /><br /><br />

        <Text fontSize="6xl" color='blue.600' as='b'>
        Learn more about the newest DAO in town!
        </Text>

        <br /><br />

        <Button
          bg="blue.500"
          color="white"
          colorScheme='messenger' 
          variant='solid'
          w="25%"
          gap='4'
          mb={4}
          py={12}
          fontSize="3xl"
          alignItems="center"
          justifyContent="center"
          display='flex' mt='2'
          boxShadow='dark-lg' p='8' rounded='xl'
          onClick={() => router.push("/about")}
        >
          Learn More
        </Button>

        <div className="homepage-footer">
          <br /><br />
        </div>
      </Container>
      
      <Footer />
    </>
  );
};

export default Home;
